#!/usr/bin/env python
"""
JP_TOOLS/install-hooks.py
Install a pre-commit hook into a git repo that runs check.py before each commit.

Usage:
    python install-hooks.py [path-to-repo]     # defaults to cwd
    python install-hooks.py --remove [path]     # uninstall the hook
"""

import sys
import argparse
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
CHECK_PY  = TOOLS_DIR / "check.py"

HOOK_MARKER = "# JP_TOOLS pre-commit hook"

HOOK_TEMPLATE = r"""#!/bin/sh
{marker}
# Auto-generated by JP_TOOLS/install-hooks.py
# Runs check.py against staged files before committing.

TOOLS_DIR="{tools_dir}"
CHECK_PY="$TOOLS_DIR/check.py"

# Collect staged files
STAGED=$(git diff --cached --name-only --diff-filter=ACM)
if [ -z "$STAGED" ]; then
    exit 0
fi

# Run check.py against the repo root
# Use --pretty for readable output on failure
python "$CHECK_PY" . --pretty
STATUS=$?

if [ $STATUS -ne 0 ]; then
    echo ""
    echo "====================================="
    echo " Pre-commit check FAILED"
    echo " Fix the issues above, then re-commit"
    echo " To skip: git commit --no-verify"
    echo "====================================="
    exit 1
fi

exit 0
"""


def install(repo_path: Path):
    git_dir = repo_path / ".git"
    if not git_dir.is_dir():
        print(f"Error: {repo_path} is not a git repository (.git not found)")
        sys.exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    hook_file = hooks_dir / "pre-commit"

    # Check for existing hook
    if hook_file.exists():
        content = hook_file.read_text(encoding="utf-8", errors="replace")
        if HOOK_MARKER in content:
            print(f"JP_TOOLS hook already installed at {hook_file}")
            print("Use --remove to uninstall first.")
            return
        # There's a non-JP_TOOLS hook — don't clobber it
        print(f"Warning: existing pre-commit hook found at {hook_file}")
        print("Appending JP_TOOLS check. Review the hook if needed.")
        # Append to existing hook
        with open(hook_file, "a", encoding="utf-8") as f:
            f.write("\n" + HOOK_TEMPLATE.format(
                marker=HOOK_MARKER,
                tools_dir=str(TOOLS_DIR).replace("\\", "/"),
            ))
    else:
        hook_file.write_text(
            HOOK_TEMPLATE.format(
                marker=HOOK_MARKER,
                tools_dir=str(TOOLS_DIR).replace("\\", "/"),
            ),
            encoding="utf-8",
        )

    # Make executable (matters on Linux/Mac, no-op on Windows)
    hook_file.chmod(0o755)
    print(f"Installed JP_TOOLS pre-commit hook at {hook_file}")
    print(f"Checks will run: python {CHECK_PY} .")


def remove(repo_path: Path):
    hook_file = repo_path / ".git" / "hooks" / "pre-commit"
    if not hook_file.exists():
        print("No pre-commit hook found.")
        return

    content = hook_file.read_text(encoding="utf-8", errors="replace")
    if HOOK_MARKER not in content:
        print("Pre-commit hook exists but is not from JP_TOOLS. Leaving it alone.")
        return

    # If the whole file is our hook, just delete it
    lines = content.split("\n")
    marker_idx = None
    for i, line in enumerate(lines):
        if HOOK_MARKER in line:
            marker_idx = i
            break

    if marker_idx is not None and marker_idx <= 1:
        # Our hook is the whole file (or starts at line 0-1)
        hook_file.unlink()
        print(f"Removed JP_TOOLS pre-commit hook from {hook_file}")
    else:
        # Our hook was appended — remove just our section
        before = lines[:marker_idx]
        hook_file.write_text("\n".join(before).rstrip() + "\n", encoding="utf-8")
        print(f"Removed JP_TOOLS section from {hook_file} (kept existing hook)")


def main():
    parser = argparse.ArgumentParser(description="Install/remove JP_TOOLS pre-commit hook")
    parser.add_argument("path", nargs="?", default=".",
                        help="Path to git repository (default: cwd)")
    parser.add_argument("--remove", action="store_true",
                        help="Remove the JP_TOOLS hook")
    args = parser.parse_args()

    repo = Path(args.path).resolve()
    if args.remove:
        remove(repo)
    else:
        install(repo)


if __name__ == "__main__":
    main()
