#!/usr/bin/env python
"""
JP_TOOLS/install-hooks.py
Install a pre-commit hook into a git repo that runs check.py before each commit.

Usage:
    python install-hooks.py [path-to-repo]     # defaults to cwd
    python install-hooks.py --remove [path]     # uninstall the hook
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path


def _tools_dir() -> Path:
    """Where to record as the install-time fallback.

    If this file lives in a git WORKTREE, record the MAIN checkout instead. A
    worktree path is transient -- `git worktree remove` deletes it -- and a hook
    pointing at one breaks on the very machine it was installed on. Measured
    2026-09-01: batocera-watch's hook pointed at JP_TOOLS.worktrees/master. #40.
    """
    here = Path(__file__).resolve().parent
    try:
        out = subprocess.run(["git", "-C", str(here), "rev-parse",
                              "--path-format=absolute", "--git-dir", "--git-common-dir"],
                             capture_output=True, text=True, check=False)
        if out.returncode == 0:
            lines = out.stdout.split()
            if len(lines) == 2 and lines[0] != lines[1]:
                # In a worktree: the main checkout is the parent of the common dir.
                main = Path(lines[1]).parent
                if (main / "check.py").exists():
                    return main
    except OSError:
        pass
    return here


TOOLS_DIR = _tools_dir()
CHECK_PY  = TOOLS_DIR / "check.py"
METHODOLOGY_DOC = TOOLS_DIR / "METHODOLOGY.md"

HOOK_MARKER = "# JP_TOOLS pre-commit hook"

# THE INSTALLED HOOK IS A SHIM (#65 part 3; the design, voted unanimously on
# 2026-09-14, is on JP_TOOLS #65). It used to be a full copy of the template,
# taken at install time, so every template change needed a reinstall in every
# repo and nothing prompted one. Now the checks live once, in JP_TOOLS'
# hooks/pre-commit.sh, and this shim runs them from the tree it resolves. What
# can go stale moves from each repo to each box's JP_TOOLS pull, so the shim
# checks that tree instead: it must be at its own origin/master (compared
# locally, no fetch, so it can be behind the forge), unless a person named it
# with JP_TOOLS_DIR, which is honoured on any branch and announced on every
# commit. Every refusal says what clears it, and nothing is skipped.
SHIM_API = 1
SHIM_TEMPLATE = r"""#!/bin/sh
{marker}
# JP_TOOLS pre-commit SHIM, interface __API__. Auto-generated by install-hooks.py.
# It never changes: every commit runs JP_TOOLS' own hooks/pre-commit.sh from
# the tree found below. That tree is checked instead. See JP_TOOLS #65.
JP_TOOLS_HOOK_API=__API__

broken() {{
    echo ""
    echo "====================================="
    echo " JP_TOOLS hook is BROKEN: $1"
    echo " NOTHING WAS CHECKED. This is not a problem with your changes."
    echo " Fix: $2"
    echo " To commit without the gate: git commit --no-verify"
    echo "====================================="
    exit 1
}}

# A named tree that is not there is refused, never passed over for another.
if [ -n "$JP_TOOLS_DIR" ] && [ ! -f "$JP_TOOLS_DIR/check.py" ]; then
    broken "JP_TOOLS_DIR=$JP_TOOLS_DIR has no check.py." \
        "unset JP_TOOLS_DIR, or point it at a JP_TOOLS tree."
fi

# WHERE JP_TOOLS LIVES IS A PROPERTY OF THE MACHINE, resolved at commit time.
# The first tree found is THE tree: one that is too old or off master is
# refused, not skipped in favour of the next.
TOOLS_DIR=""
for cand in "$JP_TOOLS_DIR" "$HOME/projects/JP_TOOLS" "$HOME/JP_TOOLS" "{tools_dir}"; do
    if [ -n "$cand" ] && [ -f "$cand/check.py" ]; then
        TOOLS_DIR="$cand"
        break
    fi
done
if [ -z "$TOOLS_DIR" ]; then
    broken "cannot find JP_TOOLS. Searched \$JP_TOOLS_DIR (currently: ${{JP_TOOLS_DIR:-unset}}), $HOME/projects/JP_TOOLS, $HOME/JP_TOOLS and {tools_dir} (recorded at install time)." \
        "export JP_TOOLS_DIR=/path/to/JP_TOOLS, or re-run install-hooks.py on this machine."
fi

BRANCH=$(git -C "$TOOLS_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')
SHORT=$(git -C "$TOOLS_DIR" rev-parse --short HEAD 2>/dev/null || echo '?')
if [ ! -f "$TOOLS_DIR/hooks/pre-commit.sh" ]; then
    broken "the JP_TOOLS at $TOOLS_DIR ($BRANCH $SHORT) is too old for this hook: it has no hooks/pre-commit.sh." \
        "git -C \"$TOOLS_DIR\" pull --ff-only"
fi

if [ -n "$JP_TOOLS_DIR" ]; then
    # Named on purpose, so any branch is honoured, and said out loud every
    # time: an exported variable outlives the test it was set for.
    echo "JP_TOOLS hook: JP_TOOLS_DIR is set; running $TOOLS_DIR on $BRANCH $SHORT (not required to be master)." >&2
else
    HEAD_SHA=$(git -C "$TOOLS_DIR" rev-parse HEAD 2>/dev/null)
    MASTER=$(git -C "$TOOLS_DIR" rev-parse -q --verify origin/master 2>/dev/null || git -C "$TOOLS_DIR" rev-parse -q --verify master 2>/dev/null)
    if [ -z "$HEAD_SHA" ] || [ "$HEAD_SHA" != "$MASTER" ]; then
        broken "the JP_TOOLS at $TOOLS_DIR is on $BRANCH $SHORT, not at its origin/master (compared locally, no fetch)." \
            "git -C \"$TOOLS_DIR\" checkout master && git -C \"$TOOLS_DIR\" pull --ff-only"
    fi
fi

export TOOLS_DIR JP_TOOLS_HOOK_API
exec sh "$TOOLS_DIR/hooks/pre-commit.sh"
""".replace("__API__", str(SHIM_API))


def _refuse_symlink(hook_file: Path, verb: str) -> None:
    """Exit 2 if the hook is a symlink, dangling or not, naming its target.

    Every write below follows a link: open(..., "a"), write_text(), chmod()
    and read_text(). A repo that ships its own hook as a tracked file and links
    it into .git/hooks (projectbook's hooks/install.sh does) would get the
    JP_TOOLS hook appended INTO THE TRACKED FILE, and its mode changed. A
    dangling link is worse: write_text() creates the target. Replacing the
    link instead would silently disable the repo's own hook. So refuse, and
    say what to do. #67.
    """
    if hook_file.is_symlink():
        print(f"Refusing to {verb}: {hook_file} is a symlink to "
              f"{os.readlink(hook_file)}.")
        print("Writing through it would change the file it points to, which is "
              "usually tracked in the repo.")
        print("Add a step to that repo's own hook that runs check.py instead.")
        print("Removing the link and re-running this would REPLACE that repo's "
              "hook, not add to it: the repo's own checks would stop running.")
        sys.exit(2)


def install(repo_path: Path) -> None:
    git_dir = repo_path / ".git"
    if not git_dir.is_dir():
        print(f"Error: {repo_path} is not a git repository (.git not found)")
        sys.exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    hook_file = hooks_dir / "pre-commit"
    _refuse_symlink(hook_file, "install")

    # Check for existing hook
    if hook_file.exists():
        content = hook_file.read_text(encoding="utf-8", errors="replace")
        if HOOK_MARKER in content:
            print(f"JP_TOOLS hook already installed at {hook_file}")
            print("Use --remove to uninstall first.")
            return
        # There's a non-JP_TOOLS hook — don't clobber it
        print(f"Warning: existing pre-commit hook found at {hook_file}")
        print("Appending JP_TOOLS check. Review the hook if needed.")
        # Append to the existing hook WITHOUT the template's own shebang. The
        # repo's hook already starts with one, and remove() keeps every line
        # above the marker, so an appended shebang survived each --remove and
        # every reinstall added another: romtools went from 1 to 2. With the
        # shebang dropped the marker is the first appended line, and remove()
        # gives back the repo's hook as it was. #66.
        body = SHIM_TEMPLATE.format(
            marker=HOOK_MARKER,
            tools_dir=str(TOOLS_DIR).replace("\\", "/"),
        )
        if body.startswith("#!"):
            body = body.split("\n", 1)[1]
        with open(hook_file, "a", encoding="utf-8") as f:
            f.write("\n" + body)
    else:
        hook_file.write_text(
            SHIM_TEMPLATE.format(
                marker=HOOK_MARKER,
                tools_dir=str(TOOLS_DIR).replace("\\", "/"),
            ),
            encoding="utf-8",
        )

    # Make executable (matters on Linux/Mac, no-op on Windows)
    hook_file.chmod(0o755)
    print(f"Installed JP_TOOLS pre-commit hook at {hook_file}")
    print(f"Checks will run: {CHECK_PY} against each staged file")
    print()
    print("This project now follows JP_TOOLS methodology.")
    print(f"Read it: {METHODOLOGY_DOC}")


def remove(repo_path: Path) -> None:
    hook_file = repo_path / ".git" / "hooks" / "pre-commit"
    _refuse_symlink(hook_file, "remove")
    if not hook_file.exists():
        print("No pre-commit hook found.")
        return

    content = hook_file.read_text(encoding="utf-8", errors="replace")
    if HOOK_MARKER not in content:
        print("Pre-commit hook exists but is not from JP_TOOLS. Leaving it alone.")
        return

    # If the whole file is our hook, just delete it
    lines = content.split("\n")
    marker_idx = None
    for i, line in enumerate(lines):
        if HOOK_MARKER in line:
            marker_idx = i
            break

    if marker_idx is not None and marker_idx <= 1:
        # Our hook is the whole file (or starts at line 0-1)
        hook_file.unlink()
        print(f"Removed JP_TOOLS pre-commit hook from {hook_file}")
    else:
        # Our section was appended. install() writes exactly "\n" + the marker
        # onward, so cut at that offset and the repo's hook comes back byte for
        # byte, whatever its ending. Splitting into lines and rstrip()ing
        # rewrote a hook with no final newline or a trailing blank line
        # (projectbook-helper, reviewing #74). An install from before #66 also
        # left its own "#!/bin/sh" just above the marker; strip that too, so
        # older installs come back clean.
        before = content[:content.index("\n" + HOOK_MARKER)]
        if before.endswith("\n#!/bin/sh"):
            before = before[:-len("\n#!/bin/sh")]
        hook_file.write_text(before, encoding="utf-8")
        print(f"Removed JP_TOOLS section from {hook_file} (kept existing hook)")


def hook_status(repo: Path) -> tuple[str, str]:
    """(STATE, detail) for one repo's pre-commit hook. #65, part 2.

    An installed hook never updates itself, and nothing said so: on
    2026-09-14 all three on joe-MacBookAir were the pre-#41 template, and one
    baked a worktree path that had gone stale (#40). CURRENT means the JP_TOOLS
    section is exactly what this JP_TOOLS would install today for the same
    recorded path. STALE says why, so the fix is a reinstall.
    """
    hook = repo / ".git" / "hooks" / "pre-commit"
    if hook.is_symlink():
        return "SYMLINK", f"-> {os.readlink(hook)} (the repo's own hook; install refuses it)"
    if not hook.exists():
        return "NONE", ""
    content = hook.read_text(encoding="utf-8", errors="replace")
    if HOOK_MARKER not in content:
        return "NOT-JP_TOOLS", ""
    section = content[content.index(HOOK_MARKER):]
    m = re.search(r'for cand in .* "([^"]*)"; do', section)
    if m is None:
        return "STALE", "no run-time JP_TOOLS lookup: installed before #41"
    expected = SHIM_TEMPLATE.format(marker=HOOK_MARKER, tools_dir=m.group(1))
    expected = expected[expected.index(HOOK_MARKER):]
    if section.rstrip("\n") == expected.rstrip("\n"):
        return "CURRENT", f"records {m.group(1)}"
    return "STALE", "differs from this JP_TOOLS' template"


def status(roots: list[Path]) -> int:
    """Report every repo's hook under `roots`; exit 1 if any is STALE."""
    repos: list[Path] = []
    for root in roots:
        if (root / ".git").is_dir():
            repos.append(root)
            continue
        # A worktree has a .git FILE and shares its main repo's hooks, so it
        # is reported there, not twice.
        repos.extend(sorted(d for d in root.iterdir() if (d / ".git").is_dir()))
    stale = 0
    for repo in repos:
        state, detail = hook_status(repo)
        stale += state == "STALE"
        print(f"{state:<13} {repo}{'  ' + detail if detail else ''}")
    print(f"{len(repos)} repos, {stale} STALE" + (": reinstall each with "
          "install-hooks.py --remove, then install-hooks.py" if stale else ""))
    return 1 if stale else 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Install/remove JP_TOOLS pre-commit hook")
    parser.add_argument("path", nargs="?", default=".",
                        help="Path to git repository (default: cwd)")
    parser.add_argument("--remove", action="store_true",
                        help="Remove the JP_TOOLS hook")
    parser.add_argument("--status", nargs="*", metavar="ROOT",
                        help="Report whether each repo's installed hook is current "
                             "(default root: ~/projects); exit 1 if any is stale")
    args = parser.parse_args()

    if args.status is not None:
        roots = [Path(r).resolve() for r in args.status] or [Path.home() / "projects"]
        sys.exit(status(roots))
    repo = Path(args.path).resolve()
    if args.remove:
        remove(repo)
    else:
        install(repo)


if __name__ == "__main__":
    main()
